### ISSUE TITLE
Links

### ISSUE THREAD

**Issue by ghost** [weimingtom/wmt_vn_study#1]
## NVList
https://github.com/anonl/nvlist
## ONSlaught
https://github.com/Helios-vmg/ONSlaught
### Note
Thank you for all of your work.
If you are interested I have written about NScripter and related engines in French:
* [Original article in French](https://fr.wikipedia.org/wiki/NScripter)
* [Machine-translated in Mandarin](https://fr-m-wikipedia-org.translate.goog/wiki/NScripter?_x_tr_sl=auto&_x_tr_tl=zh-CN&_x_tr_hl=fr)
* [Machine-translated in English](https://fr-m-wikipedia-org.translate.goog/wiki/NScripter?_x_tr_sl=auto&_x_tr_tl=en&_x_tr_hl=fr)

**Comment by weimingtom** [comment]
No, I am just studying a very old version of onscripter-en, and try to port it to csharp and unity

**Comment by weimingtom** [comment]
I don't have exe binary (only build with visual studio by myself, not good), there are some on https://github.com/onsshare/onscripter/releases, but too old.

**Comment by ilkaisernova** [comment]
I asked some internet people to help me to build the latest version of onscripter and either they can't either they do not have the time to.
The onsshare link has an old version of it as you said, but it's modified for the chinese audience, it's no use for me.
By the way, I already have ons-en and pons.

**Comment by weimingtom** [comment]
I can help you, but need some days because of my busy jobs
