### ISSUE TITLE
恋愛シミュレーションツクール２, 恋爱游戏制作大师2

### ISSUE THREAD

**Issue by ghost** [weimingtom/wmt_vn_study#2]
Hello!
Sorry to bother but I don't know how to follow the steps you wrote.
I would like to download [恋愛シミュレーションツクール２, 恋爱游戏制作大师2](https://github.com/weimingtom/wmt_vn_study#%E6%81%8B%E6%84%9B%E3%82%B7%E3%83%9F%E3%83%A5%E3%83%AC%E3%83%BC%E3%82%B7%E3%83%A7%E3%83%B3%E3%83%84%E3%82%AF%E3%83%BC%E3%83%AB%EF%BC%92-%E6%81%8B%E7%88%B1%E6%B8%B8%E6%88%8F%E5%88%B6%E4%BD%9C%E5%A4%A7%E5%B8%882).

How do I search for baidupan and use it?
However, I would like to be sure I can get the software, can you upload it somewhere like on mediafire or anonfile?
Have a good day.

**Comment by weimingtom** [comment]
1vAsv__akxIwoqVGeUU33zg

**Comment by weimingtom** [comment]
https://pan.baidu.com/s

**Comment by weimingtom** [comment]
from here, https://www.xiaobaipan.com/file-10886744.html, 恋爱游戏创作大师2.exe

**Comment by weimingtom** [comment]
seem originally from 星空网, you can find it from comicat, but i can't get it through magnet link hidden in html

**Comment by weimingtom** [comment]
it's a chinese game by someone or company (T-Time from Taiwan? or just hacked program), not japanese. Japanese version is not found, might be bought from amazon

**Comment by ilkaisernova** [comment]
Thank you, but I have no baidu account, I had to follow [this tutorial](https://www.youtube.com/watch?v=_TzjBR0RJM8).
The software works pretty well in a virtual machine on Windows XP, what OS Windows did you use?
T-Time is a company from Taiwan yes https://vndb.org/p66
What is that hacked exe?

**Comment by ilkaisernova** [comment]
Thank you for that.
I'm thinking of translating the engine or something, maybe you have an idea on how to do that?

**Comment by weimingtom** [comment]
https://www.mediafire.com/folder/v4vbydiimxhyf/renai2

**Comment by weimingtom** [comment]
mdf can be loaded with ultraiso or daemon

**Comment by weimingtom** [comment]
I have no idea how to translate this to english or other, may be not very hard

**Comment by ilkaisernova** [comment]
Thanks I'll look into it
